### ISSUE TITLE
[Bug]开启协程状态下，启动Spring Boot项目失败

### ISSUE THREAD

**Issue by A11enHuang** [alibaba/dragonwell11#191]
在启动Spring Boot时会卡死，在创建ApachePulsar Producer时一直被阻塞，但是在关闭协程时不会有此问题

Spring Boot版本: 2.3.7  + Spring WebFlux
JVM参数: 
-XX:+UseG1GC
-XX:MaxGCPauseMillis=200
-XX:+UnlockExperimentalVMOptions
-XX:+UseWisp2
-Dio.netty.noUnsafe=true

jstack如下:
"main" #1 prio=5 os_prio=0 cpu=11499.90ms elapsed=428.23s tid=0x00007f06b0026b50 nid=0x8 waiting on condition  [0x00007f06b997b000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park0(java.base@11.0.13.9/Native Method)
        - parking to wait for  <0x000000066273fd00> (a java.util.concurrent.CompletableFuture$Signaller)
        at jdk.internal.misc.Unsafe$1.park0(java.base@11.0.13.9/Unsafe.java:73)
        at com.alibaba.wisp.engine.WispTask.parkInternal(java.base@11.0.13.9/WispTask.java:410)
        at com.alibaba.wisp.engine.WispTask.jdkPark(java.base@11.0.13.9/WispTask.java:460)
        at com.alibaba.wisp.engine.WispEngine$5.park(java.base@11.0.13.9/WispEngine.java:277)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.13.9/Unsafe.java:2324)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.13.9/LockSupport.java:194)
        at java.util.concurrent.CompletableFuture$Signaller.block(java.base@11.0.13.9/CompletableFuture.java:1796)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@11.0.13.9/ForkJoinPool.java:3128)
        at java.util.concurrent.CompletableFuture.waitingGet(java.base@11.0.13.9/CompletableFuture.java:1823)
        at java.util.concurrent.CompletableFuture.get(java.base@11.0.13.9/CompletableFuture.java:1998)
        at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:93)

**Comment by yuleil** [comment]
您好，目前Dragonwell11支持Wisp的版本还在pre-release的状态，尚未正式发布。
请问可以提供更加完整点的jstack吗？

**Comment by A11enHuang** [comment]
完整的jstack如下,最终是卡在了ProducerBuilder的created()方法

Full thread dump OpenJDK 64-Bit Server VM (11.0.13.9+0 mixed mode):

Threads class SMR info:
_java_thread_list=0x00007f31dc003a10, length=14, elements={
0x00007f3230026940, 0x00007f32302b7d90, 0x00007f32302bb6e0, 0x00007f32302d9b60,
0x00007f32302db500, 0x00007f32302dd080, 0x00007f32302e0b70, 0x00007f32302e2520,
0x00007f32303db4b0, 0x00007f32303e3840, 0x00007f32303e5680, 0x00007f32303e69d0,
0x00007f3230b36d90, 0x00007f31dc0024a0
}

"main" #1 prio=5 os_prio=0 cpu=12392.77ms elapsed=88.98s tid=0x00007f3230026940 nid=0x9 waiting on condition  [0x00007f323a5a0000]
   java.lang.Thread.State: WAITING (parking)
        at ***@***.***/Native Method)
        - parking to wait for  <0x0000000695f481b0> (a java.util.concurrent.CompletableFuture$Signaller)
        at ***@***.***/Unsafe.java:73)
        at ***@***.***/WispTask.java:410)
        at ***@***.***/WispTask.java:460)
        at ***@***.***/WispEngine.java:277)
        at ***@***.***/Unsafe.java:2324)
        at ***@***.***/LockSupport.java:194)
        at ***@***.***/CompletableFuture.java:1796)
        at ***@***.***/ForkJoinPool.java:3128)
        at ***@***.***/CompletableFuture.java:1823)
        at ***@***.***/CompletableFuture.java:1998)
        at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:93)
        at com.xxx.service.ApachePulsarProudcerBuilder
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
        - locked <0x000000068cce6048> (a java.util.concurrent.ConcurrentHashMap)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1828)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1265)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:886)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:790)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1356)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1203)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$248/0x00000008002e9040.getObject(Unknown Source)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        - locked <0x000000068cce6048> (a java.util.concurrent.ConcurrentHashMap)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        - locked <0x000000068ca4b660> (a java.lang.Object)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:62)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at com.xxxx.WebApplication.main(WebApplication.java:20)
        at ***@***.***/Native Method)
        at ***@***.***/NativeMethodAccessorImpl.java:62)
        at ***@***.***/DelegatingMethodAccessorImpl.java:43)
        at ***@***.***/Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=10.57ms elapsed=88.94s tid=0x00007f32302b7d90 nid=0x10 waiting on condition  [0x00007f3218115000]
   java.lang.Thread.State: RUNNABLE
        at ***@***.***/Native Method)
        at ***@***.***/Reference.java:241)
        at ***@***.***/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=1.73ms elapsed=88.94s tid=0x00007f32302bb6e0 nid=0x11 waiting on condition  [0x00007f320451d000]
   java.lang.Thread.State: WAITING (parking)
        at ***@***.***/Native Method)
        at ***@***.***/Unsafe.java:73)
        at ***@***.***/WispTask.java:410)
        at ***@***.***/WispTask.java:471)
        at ***@***.***/Native Method)
        at ***@***.***/ReferenceQueue.java:155)
        - waiting to lock <0x000000060a521278> (a java.lang.ref.ReferenceQueue$Lock)
        at ***@***.***/ReferenceQueue.java:176)
        at ***@***.***/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.77ms elapsed=88.92s tid=0x00007f32302d9b60 nid=0x12 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=44.43ms elapsed=88.92s tid=0x00007f32302db500 nid=0x13 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=0 cpu=12853.08ms elapsed=88.92s tid=0x00007f32302dd080 nid=0x14 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #7 daemon prio=9 os_prio=0 cpu=4134.39ms elapsed=88.92s tid=0x00007f32302e0b70 nid=0x15 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #8 daemon prio=9 os_prio=0 cpu=7.56ms elapsed=88.92s tid=0x00007f32302e2520 nid=0x16 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #10 daemon prio=8 os_prio=0 cpu=15.93ms elapsed=88.83s tid=0x00007f32303db4b0 nid=0x17 runnable  [0x00007f31fced1000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at ***@***.***/Native Method)
        - waiting on <0x000000060a45bdb0> (a java.lang.ref.ReferenceQueue$Lock)
        at ***@***.***/ReferenceQueue.java:155)
        - waiting to lock <0x000000060a45bdb0> (a java.lang.ref.ReferenceQueue$Lock)
        at ***@***.***/CleanerImpl.java:148)
        at ***@***.***/Thread.java:955)
        at ***@***.***/InnocuousThread.java:134)

"Wisp-Unpark-Dispatcher" #11 daemon prio=5 os_prio=0 cpu=0.35ms elapsed=88.82s tid=0x00007f32303e3840 nid=0x18 runnable  [0x00007f31fcbcd000]
   java.lang.Thread.State: RUNNABLE
        at ***@***.***/Native Method)
        at ***@***.***/WispEngine.java:188)
        at ***@***.***/Thread.java:955)

"Wisp-Sysmon" #12 daemon prio=5 os_prio=0 cpu=71.00ms elapsed=88.82s tid=0x00007f32303e5680 nid=0x19 waiting on condition  [0x00007f31fcacc000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at ***@***.***/Native Method)
        at ***@***.***/Unsafe.java:73)
        at ***@***.***/WispSysmon.java:75)
        at ***@***.***/Unknown Source)
        at ***@***.***/Thread.java:955)

"Wisp-Root-Worker-0" #9 daemon prio=5 os_prio=0 cpu=147.73ms elapsed=88.82s tid=0x00007f32303e69d0 nid=0x1a runnable  [0x00007f31b9125000]
   java.lang.Thread.State: RUNNABLE
        at org.apache.pulsar.shade.io.netty.channel.epoll.Native.epollWait(Native Method)
        at org.apache.pulsar.shade.io.netty.channel.epoll.Native.epollWait(Native.java:177)
        at org.apache.pulsar.shade.io.netty.channel.epoll.Native.epollWait(Native.java:170)
        at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:290)
        at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:347)
        at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at ***@***.***/Thread.java:955)
        at ***@***.***/WispTask.java:285)
        at ***@***.***/WispTask.java:274)
        at ***@***.***/WispTask.java:246)
        at ***@***.***/CoroutineBase.java:74)

 - Coroutine [0x7f31bc00fbf0] "pulsar-client-io-1-1" #11 active=1 steal=0 steal_fail=0 preempt=0 park=0/0 containerId=0 cg=0/0 ttr=0

 - Coroutine [0x7f31bc000a40] "Wisp-Root-Worker-0" #2 active=564 steal=0 steal_fail=0 preempt=0 park=0/0 containerId=0 cg=0/0 ttr=0
        at ***@***.***/CoroutineSupport.java:170)
        at ***@***.***/WispTask.java:314)
        at ***@***.***/WispCarrier.java:413)
        at ***@***.***/WispCarrier.java:151)
        at ***@***.***/TaskDispatcher.java:45)
        at ***@***.***/WispScheduler.java:537)
        at ***@***.***/WispScheduler.java:162)
        at ***@***.***/WispScheduler.java:142)
        at ***@***.***/Thread.java:955)

 - Coroutine [0x7f31bc00de40] "sentinel-heartbeat-send-task-thread-1" #10 active=1 steal=0 steal_fail=0 preempt=0 park=0/-1 containerId=0 cg=0/0 ttr=0
        at ***@***.***/CoroutineSupport.java:170)
        - parking to wait for  <0x000000068c38e9e0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at ***@***.***/WispTask.java:314)
        at ***@***.***/WispCarrier.java:413)
        at ***@***.***/WispCarrier.java:262)
        at ***@***.***/WispTask.java:408)
        at ***@***.***/WispTask.java:460)
        at ***@***.***/WispEngine.java:277)
        at ***@***.***/Unsafe.java:2329)
        at ***@***.***/LockSupport.java:234)
        at ***@***.***/AbstractQueuedSynchronizer.java:2132)
        at ***@***.***/ScheduledThreadPoolExecutor.java:1182)
        at ***@***.***/ScheduledThreadPoolExecutor.java:899)
        at ***@***.***/ThreadPoolExecutor.java:1054)
        at ***@***.***/ThreadPoolExecutor.java:1114)
        at ***@***.***/ThreadPoolExecutor.java:628)
        at ***@***.***/Thread.java:955)
        at ***@***.***/WispTask.java:285)
        at ***@***.***/WispTask.java:274)
        at ***@***.***/WispTask.java:246)
        at ***@***.***/CoroutineBase.java:74)

 - Coroutine [0x7f31bc008a30] "sentinel-command-center-executor-thread-1" #8 active=1 steal=0 steal_fail=0 preempt=0 park=0/-1 containerId=0 cg=0/0 ttr=0
        at ***@***.***/CoroutineSupport.java:170)
        at ***@***.***/WispTask.java:314)
        at ***@***.***/WispCarrier.java:413)
        at ***@***.***/WispCarrier.java:262)
        at ***@***.***/WispTask.java:408)
        at ***@***.***/WispTask.java:460)
        at ***@***.***/WispEngine.java:277)
        at ***@***.***/WispServerSocketImpl.java:99)
        at ***@***.***/WispServerSocketImpl.java:82)
        at ***@***.***/ServerSocket.java:571)
        at com.alibaba.csp.sentinel.transport.command.SimpleHttpCommandCenter$ServerThread.run(SimpleHttpCommandCenter.java:188)
        at ***@***.***/Executors.java:515)
        at ***@***.***/FutureTask.java:264)
        at ***@***.***/ThreadPoolExecutor.java:1128)
        at ***@***.***/ThreadPoolExecutor.java:628)
        at ***@***.***/Thread.java:955)
        at ***@***.***/WispTask.java:285)
        at ***@***.***/WispTask.java:274)
        at ***@***.***/WispTask.java:246)
        at ***@***.***/CoroutineBase.java:74)

 - Coroutine [0x7f31bc006f40] "com.alibaba.nacos.client.Worker.fixed-10.146.0.3_8848-5132cda0-0428-4904-9a57-45c408e214cf" #7 active=552 steal=0 steal_fail=0 preempt=0 park=0/-1 containerId=0 cg=0/0 ttr=0
        at ***@***.***/CoroutineSupport.java:170)
        - parking to wait for  <0x000000068cdd35d0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at ***@***.***/WispTask.java:314)
        at ***@***.***/WispCarrier.java:413)
        at ***@***.***/WispCarrier.java:262)
        at ***@***.***/WispTask.java:408)
        at ***@***.***/WispTask.java:460)
        at ***@***.***/WispEngine.java:277)
        at ***@***.***/Unsafe.java:2329)
        at ***@***.***/LockSupport.java:234)
        at ***@***.***/AbstractQueuedSynchronizer.java:2132)
        at ***@***.***/ScheduledThreadPoolExecutor.java:1182)
        at ***@***.***/ScheduledThreadPoolExecutor.java:899)
        at ***@***.***/ThreadPoolExecutor.java:1054)
        at ***@***.***/ThreadPoolExecutor.java:1114)
        at ***@***.***/ThreadPoolExecutor.java:628)
        at ***@***.***/Thread.java:955)
        at ***@***.***/WispTask.java:285)
        at ***@***.***/WispTask.java:274)
        at ***@***.***/WispTask.java:246)
        at ***@***.***/CoroutineBase.java:74)

 - Coroutine [0x7f31bc005630] "com.alibaba.nacos.client.config.security.updater" #6 active=2 steal=0 steal_fail=0 preempt=0 park=0/-1 containerId=0 cg=0/0 ttr=0
        at ***@***.***/CoroutineSupport.java:170)
        - parking to wait for  <0x000000068cdd2b10> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at ***@***.***/WispTask.java:314)
        at ***@***.***/WispCarrier.java:413)
        at ***@***.***/WispCarrier.java:262)
        at ***@***.***/WispTask.java:408)
        at ***@***.***/WispTask.java:460)
        at ***@***.***/WispEngine.java:277)
        at ***@***.***/Unsafe.java:2329)
        at ***@***.***/LockSupport.java:234)
        at ***@***.***/AbstractQueuedSynchronizer.java:2132)
        at ***@***.***/ScheduledThreadPoolExecutor.java:1182)
        at ***@***.***/ScheduledThreadPoolExecutor.java:899)
        at ***@***.***/ThreadPoolExecutor.java:1054)
        at ***@***.***/ThreadPoolExecutor.java:1114)
        at ***@***.***/ThreadPoolExecutor.java:628)
        at ***@***.***/Thread.java:955)
        at ***@***.***/WispTask.java:285)
        at ***@***.***/WispTask.java:274)
        at ***@***.***/WispTask.java:246)
        at ***@***.***/CoroutineBase.java:74)

 - Coroutine [0x7f31bc003dd0] "Keep-Alive-Timer" #5 active=2 steal=0 steal_fail=0 preempt=0 park=0/-1 containerId=0 cg=0/0 ttr=0
        at ***@***.***/CoroutineSupport.java:170)
        at ***@***.***/WispTask.java:314)
        at ***@***.***/WispCarrier.java:413)
        at ***@***.***/WispCarrier.java:262)
        at ***@***.***/WispTask.java:408)
        at ***@***.***/WispTask.java:460)
        at ***@***.***/WispTask.java:343)
        at ***@***.***/WispEngine.java:256)
        at ***@***.***/Thread.java:396)
        at ***@***.***/KeepAliveCache.java:168)
        at ***@***.***/Thread.java:955)
        at ***@***.***/InnocuousThread.java:134)
        at ***@***.***/WispTask.java:285)
        at ***@***.***/WispTask.java:274)
        at ***@***.***/WispTask.java:246)
        at ***@***.***/CoroutineBase.java:74)

 - Coroutine [0x7f31bc0023c0] "Timer-0" #3 active=1 steal=0 steal_fail=0 preempt=0 park=-1/0 containerId=0 cg=0/0 ttr=0
        at ***@***.***/CoroutineSupport.java:170)
        at ***@***.***/WispTask.java:314)
        at ***@***.***/WispCarrier.java:413)
        at ***@***.***/WispCarrier.java:262)
        at ***@***.***/WispTask.java:408)
        at ***@***.***/WispTask.java:471)
        at ***@***.***/Native Method)
        at ***@***.***/Timer.java:553)
        - waiting to lock <0x000000068c5c2400> (a java.util.TaskQueue)
        at ***@***.***/Timer.java:506)
        at ***@***.***/WispTask.java:285)
        at ***@***.***/WispTask.java:274)
        at ***@***.***/WispTask.java:246)
        at ***@***.***/CoroutineBase.java:74)

"Wisp-Prevent-Shutdown-0" #23 prio=5 os_prio=0 cpu=0.53ms elapsed=78.45s tid=0x00007f3230b36d90 nid=0x1c runnable  [0x00007f31b98ce000]
   java.lang.Thread.State: WAITING (on object monitor)
        at ***@***.***/Native Method)
        - waiting on <0x000000068c38edf8> (a com.alibaba.wisp.engine.ThreadAsWisp$PreventShutdownThread)
        at ***@***.***/Object.java:328)
        at ***@***.***/ThreadAsWisp.java:153)
        - waiting to lock <0x000000068c38edf8> (a com.alibaba.wisp.engine.ThreadAsWisp$PreventShutdownThread)

"Attach Listener" #30 daemon prio=9 os_prio=0 cpu=0.57ms elapsed=0.10s tid=0x00007f31dc0024a0 nid=0x3d waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=0 cpu=96.58ms elapsed=88.95s tid=0x00007f32302afa50 nid=0xf runnable  

"GC Thread#0" os_prio=0 cpu=558.43ms elapsed=88.98s tid=0x00007f323003f4a0 nid=0xa runnable  

"G1 Main Marker" os_prio=0 cpu=2.65ms elapsed=88.97s tid=0x00007f3230079340 nid=0xb runnable  

"G1 Conc#0" os_prio=0 cpu=170.73ms elapsed=88.97s tid=0x00007f323007aa30 nid=0xc runnable  

"G1 Refine#0" os_prio=0 cpu=1.27ms elapsed=88.97s tid=0x00007f32301e0480 nid=0xd runnable  

"G1 Young RemSet Sampling" os_prio=0 cpu=20.97ms elapsed=88.97s tid=0x00007f32301e1a70 nid=0xe runnable  
"VM Periodic Task Thread" os_prio=0 cpu=57.87ms elapsed=88.82s tid=0x00007f32303e8ec0 nid=0x1b waiting on condition  

JNI global refs: 28, weak refs: 0

**Comment by joeyleeeeeee97** [comment]
Netty的native-transport阻塞了协程调度 A: 也可以使用-Dio.netty.noUnsafe=true , 其他unsafe功能可能会受影响。对于netty 4.1.25以上，支持了通过-Dio.netty.transport.noNative=true 来仅关闭jni epoll

@A11enHuang

**Comment by A11enHuang** [comment]
加了这个参数无效，如下是我配置的参数
-XX:+UnlockExperimentalVMOptions 
-XX:+UseWisp2
-Dio.netty.transport.noNative=true
我也有尝试使用 -Dio.netty.noUnsafe=true 均无效
