### ISSUE TITLE
[Bug] 使用Hutool工具类创建图形验证码的时候报错

### ISSUE THREAD

**Issue by a11enhuang** [alibaba/dragonwell11#241]
JDK 版本：`Alibaba_Dragonwell_11.0.15.11.9`
Hutool版本：
```xml
<dependency>
    <groupId>cn.hutool</groupId>
    <artifactId>hutool-captcha</artifactId>
    <version>5.7.22</version>
</dependency>
```
调用方式：
```java
GifCaptcha gifCaptcha = CaptchaUtil.createGifCaptcha(200, 100, 6);
String code = gifCaptcha.getCode();
```
异常信息：
```txt
Caused by: java.lang.NullPointerException
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262) ~[?:?]
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225) ~[?:?]
	at sun.awt.FontConfiguration.init(FontConfiguration.java:107) ~[?:?]
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719) ~[?:?]
	at sun.font.SunFontManager$2.run(SunFontManager.java:379) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at sun.font.SunFontManager.<init>(SunFontManager.java:324) ~[?:?]
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35) ~[?:?]
	at sun.awt.X11FontManager.<init>(X11FontManager.java:56) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74) ~[?:?]
	at java.awt.Font.getFont2D(Font.java:497) ~[?:?]
	at java.awt.Font$FontAccessImpl.getFont2D(Font.java:237) ~[?:?]
	at sun.font.FontUtilities.getFont2D(FontUtilities.java:158) ~[?:?]
	at sun.java2d.SunGraphics2D.checkFontInfo(SunGraphics2D.java:670) ~[?:?]
	at sun.java2d.SunGraphics2D.getFontInfo(SunGraphics2D.java:836) ~[?:?]
	at sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:46) ~[?:?]
	at sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2963) ~[?:?]
	at cn.hutool.captcha.GifCaptcha.graphicsImage(GifCaptcha.java:173) ~[hutool-captcha-5.7.22.jar!/:?]
	at cn.hutool.captcha.GifCaptcha.createCode(GifCaptcha.java:125) ~[hutool-captcha-5.7.22.jar!/:?]
	at cn.hutool.captcha.AbstractCaptcha.getCode(AbstractCaptcha.java:127) ~[hutool-captcha-5.7.22.jar!/:?]
```

**Comment by ziyilin** [comment]
可以参考下边两个链接：
https://github.com/adoptium/temurin-build/issues/693
https://github.com/AdoptOpenJDK/openjdk-docker/issues/75

**Comment by dreamkaylee** [comment]
应该是用了Alpine Linux吧
