### ISSUE TITLE
[Bug] TestThreadInfo.java/TestThreadState.java用例失败

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell11#254]
**Description**
com/alibaba/wisp/thread/TestThreadInfo.java、com/alibaba/wisp/thread/TestThreadState.java用例失败

```log
java.lang.RuntimeException: assertNotEquals: expected null to not equal null
	at jdk.testlibrary.Asserts.fail(Asserts.java:540)
	at jdk.testlibrary.Asserts.assertNotEquals(Asserts.java:398)
	at jdk.testlibrary.Asserts.assertNotNull(Asserts.java:441)
	at jdk.testlibrary.Asserts.assertNotNull(Asserts.java:430)
	at TestThreadInfo.main(TestThreadInfo.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:955)
	at java.base/com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:285)
	at java.base/com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:274)
	at java.base/com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:246)
	at java.base/java.dyn.CoroutineBase.startInternal(CoroutineBase.java:74)
```

```log
java.lang.RuntimeException: assertEquals: expected NEW to equal RUNNABLE
	at jdk.testlibrary.Asserts.fail(Asserts.java:540)
	at jdk.testlibrary.Asserts.assertEquals(Asserts.java:209)
	at jdk.testlibrary.Asserts.assertEquals(Asserts.java:193)
	at jdk.testlibrary.Asserts.assertEQ(Asserts.java:170)
	at TestThreadState.main(TestThreadState.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:955)
	at java.base/com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:285)
	at java.base/com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:274)
	at java.base/com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:246)
	at java.base/java.dyn.CoroutineBase.startInternal(CoroutineBase.java:74)
```

**Steps to Reproduce**
```bash
for i in `seq 200` ; do time jtreg -v:fail,error,nopass -ignore:quiet -r jt-report-$i -w jt-work-$i test/jdk/com/alibaba/wisp &> test-$i.log ; done
```

**Expected behavior**
run pass everytime

**JDK version**
```log
openjdk version "11.0.15.11" 2022-04-19
OpenJDK Runtime Environment (Alibaba Dragonwell)-11.0.15.11+9-GA (build 11.0.15.11+9)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell)-11.0.15.11+9-GA (build 11.0.15.11+9, mixed mode)
```

**Execution environment**

![image](https://user-images.githubusercontent.com/24123821/182119246-e29ef98e-669c-4e08-b8b0-b0cacbbd3f12.png)

**Comment by sendaoYan** [comment]
使用新版本可以正常运行
![image](https://user-images.githubusercontent.com/24123821/182138928-bf72f0e5-0fa3-4d02-be36-d64f5159e7af.png)
