### ISSUE TITLE
[Bug] wisp多个用例TestSleep.java TestPark.java TestPreemptWispInternalBug.java TestPreemptWisp2InternalBug.java TestPassToken.java TestSocket.java TestThrowError.java随机失败

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell11#255]
**Description**
test/jdk/com/alibaba/wisp/timer/TestSleep.java用例随机失败

```log
STDOUT:
ms = 90
interval = 264
STDERR:
java.lang.RuntimeException: assertTrue: expected true, was false
        at jdk.testlibrary.Asserts.fail(Asserts.java:540)
        at jdk.testlibrary.Asserts.assertTrue(Asserts.java:490)
        at jdk.testlibrary.Asserts.assertTrue(Asserts.java:476)
        at TestSleep.main(TestSleep.java:19)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:955)
```

**Steps to Reproduce**
```bash
test=test/jdk/com/alibaba/wisp/timer/TestSleep.java
dir="tmp-jtreg-"`basename $test .java` ; rm -rf $dir ; mkdir -p $dir ; time seq 100 | xargs -i -n 1 -P 100 bash -c "jtreg -timeoutFactor:8 -v:fail,error,time,nopass -nr -w $dir/index-{} $test &> $dir/{}.log ; grep 'Test results: passed: 1' -L $dir/{}.log"
```

**Expected behavior**
run pass everytime

**JDK version**
```
openjdk version "11.0.16.11" 2022-07-19
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition)-11.0.15.11+9-GA (build 11.0.16.11+9)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition)-11.0.15.11+9-GA (build 11.0.16.11+9, mixed mode)
```

**Execution environment**

![image](https://user-images.githubusercontent.com/24123821/182284271-8bab4256-ba70-4c08-9919-5b68da2d50e9.png)

**Comment by sendaoYan** [comment]
多个用例随机失败

测试命令：

```bash
time for i in `seq 200` ; do time jtreg -conc:24 -v:fail,error,nopass -ignore:quiet -a -r jt-report-$i -w jt-work-$i test/jdk/com/alibaba/wisp* &> test-$i.log ; done
```

```
com/alibaba/wisp/timer/TestSleep.java
com/alibaba/wisp/TestPark.java
com/alibaba/wisp2/bug/TestPreemptWispInternalBug.java
com/alibaba/wisp2/bug/TestPreemptWisp2InternalBug.java
com/alibaba/wisp/monitor/TestPassToken.java
com/alibaba/wisp/io/TestSocket.java
com/alibaba/wisp/thread/TestThrowError.java
```

**com/alibaba/wisp/timer/TestSleep.java**
fail概率：73/200

```log
java.lang.Error: java.util.concurrent.TimeoutException
        at TestSleep.lambda$main$1(TestSleep.java:29)
        at java.base/java.util.stream.MatchOps$2MatchSink.accept(MatchOps.java:119)
        at java.base/java.util.stream.Streams$RangeIntSpliterator.tryAdvance(Streams.java:82)
        at java.base/java.util.stream.IntPipeline.forEachWithCancel(IntPipeline.java:163)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.MatchOps$MatchTask.doLeaf(MatchOps.java:306)
        at java.base/java.util.stream.MatchOps$MatchTask.doLeaf(MatchOps.java:277)
        at java.base/java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateParallel(MatchOps.java:242)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateParallel(MatchOps.java:196)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.IntPipeline.allMatch(IntPipeline.java:518)
        at TestSleep.main(TestSleep.java:19)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:955)
Caused by: java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
        at TestSleep.lambda$main$1(TestSleep.java:27)
        ... 24 more

```



**com/alibaba/wisp/TestPark.java**
 失败概率：4/200

```log
java.util.concurrent.ExecutionException: java.lang.Error: error test unpark by other thread
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at TestPark.main(TestPark.java:66)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:955)
        at java.base/com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:301)
        at java.base/com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:290)
        at java.base/com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:262)
        at java.base/java.dyn.CoroutineBase.startInternal(CoroutineBase.java:74)
Caused by: java.lang.Error: error test unpark by other thread
        at TestPark.lambda$main$0(TestPark.java:36)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        ... 4 more
```

**com/alibaba/wisp2/bug/TestPreemptWispInternalBug.java**
fail probability: 2/200

```log
java.lang.Error: java.util.concurrent.TimeoutException
        at TestSleep.lambda$main$1(TestSleep.java:29)
        at java.base/java.util.stream.MatchOps$2MatchSink.accept(MatchOps.java:119)
        at java.base/java.util.stream.Streams$RangeIntSpliterator.tryAdvance(Streams.java:82)
        at java.base/java.util.stream.IntPipeline.forEachWithCancel(IntPipeline.java:163)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.MatchOps$MatchTask.doLeaf(MatchOps.java:306)
        at java.base/java.util.stream.MatchOps$MatchTask.doLeaf(MatchOps.java:277)
        at java.base/java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateParallel(MatchOps.java:242)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateParallel(MatchOps.java:196)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.IntPipeline.allMatch(IntPipeline.java:518)
        at TestSleep.main(TestSleep.java:19)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:955)
Caused by: java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
        at TestSleep.lambda$main$1(TestSleep.java:27)
        ... 24 more
```


**com/alibaba/wisp2/bug/TestPreemptWisp2InternalBug.java**
 fail probability:4/200

```log
Command line: [/home/yansendao/software/jdk/2022-07/j2sdk-image/bin/java -cp /home/yansendao/git/dragonwell11/jt-work-64/classes/12/com/alibaba/wisp2/bug/TestPreemptWisp2InternalBug.d:/home/yansendao/git/dragonwell11/test/jdk/com/alibaba/wisp2/bug:/home/yansendao/git/dragonwell11/jt-work-64/classes/12/test/lib:/home/yansendao/git/dragonwell11/test/lib:/home/yansendao/software/jdk/jtreg/lib/javatest.jar:/home/yansendao/software/jdk/jtreg/lib/jtreg.jar -XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 -XX:+UnlockDiagnosticVMOptions -XX:+VerboseWisp -XX:-Inline --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED TestPreemptWisp2InternalBug toString ]
STDERR:
 stdout: [];
 stderr: []
 exitValue = 0

java.lang.RuntimeException: '[WISP] preempt was blocked, because wisp internal method on the stack' missing from stdout/stderr

        at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:164)
        at TestPreemptWisp2InternalBug.main(TestPreemptWisp2InternalBug.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:955)

JavaTest Message: Test threw exception: java.lang.RuntimeException: '[WISP] preempt was blocked, because wisp internal method on the stack' missing from stdout/stderr

JavaTest Message: shutting down test
```



**com/alibaba/wisp/monitor/TestPassToken.java**
 fail probability: 5/200

```log
"MainThread" #82 prio=5 os_prio=0 cpu=13.94ms elapsed=120.16s tid=0x00007f6c2c6e8fb0 nid=0x310014 waiting on condition  [0x00007f6b58bc4000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park0(java.base@11.0.16.11/Native Method)
        at jdk.internal.misc.Unsafe$1.park0(java.base@11.0.16.11/Unsafe.java:73)
        at com.alibaba.wisp.engine.WispTask.parkInternal(java.base@11.0.16.11/WispTask.java:426)
        at com.alibaba.wisp.engine.WispTask.park(java.base@11.0.16.11/WispTask.java:487)
        at java.lang.ref.ReferenceQueue.poll(java.base@11.0.16.11/ReferenceQueue.java:119)
        - waiting to lock <0x00000000fb8c6100> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.invoke.MethodType$ConcurrentWeakInternSet.expungeStaleElements(java.base@11.0.16.11/MethodType.java:1317)
        at java.lang.invoke.MethodType$ConcurrentWeakInternSet.get(java.base@11.0.16.11/MethodType.java:1277)
        at java.lang.invoke.MethodType.makeImpl(java.base@11.0.16.11/MethodType.java:300)
        at java.lang.invoke.MethodHandleNatives.findMethodHandleType(java.base@11.0.16.11/MethodHandleNatives.java:376)
        at java.util.concurrent.ConcurrentLinkedQueue.offer(java.base@11.0.16.11/ConcurrentLinkedQueue.java:366)
        at com.alibaba.wisp.engine.WispScheduler$Worker.pushAndSignal(java.base@11.0.16.11/WispScheduler.java:254)
        at com.alibaba.wisp.engine.WispScheduler$SchedulingPolicy$2.enqueue(java.base@11.0.16.11/WispScheduler.java:436)
        at com.alibaba.wisp.engine.WispScheduler.executeWithWorkerThread(java.base@11.0.16.11/WispScheduler.java:405)
        at com.alibaba.wisp.engine.WispCarrier.wakeupTask(java.base@11.0.16.11/WispCarrier.java:293)
        at com.alibaba.wisp.engine.WispTask.unparkInternal(java.base@11.0.16.11/WispTask.java:459)
        at com.alibaba.wisp.engine.WispTask.unpark(java.base@11.0.16.11/WispTask.java:491)
        at com.alibaba.wisp.engine.WispTask.unparkById(java.base@11.0.16.11/WispTask.java:498)
        at java.lang.ref.ReferenceQueue.poll(java.base@11.0.16.11/ReferenceQueue.java:120)
        at java.lang.invoke.MethodType$ConcurrentWeakInternSet.expungeStaleElements(java.base@11.0.16.11/MethodType.java:1317)
        at java.lang.invoke.MethodType$ConcurrentWeakInternSet.get(java.base@11.0.16.11/MethodType.java:1277)
        at java.lang.invoke.MethodType.makeImpl(java.base@11.0.16.11/MethodType.java:300)
        at java.lang.invoke.MethodHandleNatives.findMethodHandleType(java.base@11.0.16.11/MethodHandleNatives.java:376)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$Node.<init>(java.base@11.0.16.11/AbstractQueuedSynchronizer.java:528)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.addWaiter(java.base@11.0.16.11/AbstractQueuedSynchronizer.java:657)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(java.base@11.0.16.11/AbstractQueuedSynchronizer.java:1033)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@11.0.16.11/AbstractQueuedSynchronizer.java:1353)
        at java.util.concurrent.CountDownLatch.await(java.base@11.0.16.11/CountDownLatch.java:232)
        at TestPassToken.lambda$doTest$4(TestPassToken.java:101)
        at TestPassToken$$Lambda$25/0x000000080009e040.accept(Unknown Source)
        at java.util.ArrayList.forEach(java.base@11.0.16.11/ArrayList.java:1541)
        at TestPassToken.doTest(TestPassToken.java:95)
        at TestPassToken.main(TestPassToken.java:60)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.16.11/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.16.11/NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.16.11/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@11.0.16.11/Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(java.base@11.0.16.11/Thread.java:955)
```


[test-95.log](https://github.com/alibaba/dragonwell11/files/9238899/test-95.log)



**com/alibaba/wisp/io/TestSocket.java** 
fail probability 2/200

```log
STDOUT:
[Socket[addr=localhost/127.0.0.1,port=13000,localport=33538], Socket[addr=/127.0.0.1,port=33538,localport=13000]]
STDERR:
java.lang.Error: not wake as expected
        at TestSocket.testBlock(TestSocket.java:46)
        at TestSocket.main(TestSocket.java:22)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:955)
```


**com/alibaba/wisp/thread/TestThrowError.java**

fail probability:  2/200

```log
java.lang.RuntimeException: assertTrue: expected true, was false
        at jdk.testlibrary.Asserts.fail(Asserts.java:540)
        at jdk.testlibrary.Asserts.assertTrue(Asserts.java:490)
        at jdk.testlibrary.Asserts.assertTrue(Asserts.java:476)
        at TestThrowError.main(TestThrowError.java:26)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:955)

JavaTest Message: Test threw exception: java.lang.RuntimeException: assertTrue: expected true, was false
JavaTest Message: shutting down test
```

**Comment by sendaoYan** [comment]
**com/alibaba/wisp/monitor/TestJNICritical.java** intermittently timeout, probability 1/200

```log
"main" #1 prio=5 os_prio=0 cpu=458.75ms elapsed=120.28s tid=0x00007f74fc027b90 nid=0x36094b waiting on condition  [0x00007f7503a4d000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park0(java.base@11.0.16.11/Native Method)
	at jdk.internal.misc.Unsafe$1.park0(java.base@11.0.16.11/Unsafe.java:73)
	at com.alibaba.wisp.engine.WispTask.parkInternal(java.base@11.0.16.11/WispTask.java:426)
	at com.alibaba.wisp.engine.WispTask.park(java.base@11.0.16.11/WispTask.java:487)
	at java.lang.Object.wait(java.base@11.0.16.11/Native Method)
	at java.lang.Thread.join(java.base@11.0.16.11/Thread.java:1450)
	- waiting to lock <0x000000008231e400> (a java.lang.Thread)
	at java.lang.Thread.join(java.base@11.0.16.11/Thread.java:1525)
	at com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)
```

[test-179.log](https://github.com/alibaba/dragonwell11/files/9239475/test-179.log)

**Comment by sendaoYan** [comment]
**com/alibaba/wisp/lock/TestLock.java** fail probability 1/200

```log
java.lang.RuntimeException: assertTrue: expected true, was false
        at jdk.testlibrary.Asserts.fail(Asserts.java:540)
        at jdk.testlibrary.Asserts.assertTrue(Asserts.java:490)
        at jdk.testlibrary.Asserts.assertTrue(Asserts.java:476)
        at TestLock.main(TestLock.java:34)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:955)
```

**Comment by sendaoYan** [comment]
**com/alibaba/wisp/thread/TestDaemon.java**  fail probability 1/200

```log
java.lang.RuntimeException: assertEquals: expected true to equal false
        at jdk.testlibrary.Asserts.fail(Asserts.java:540)
        at jdk.testlibrary.Asserts.assertEquals(Asserts.java:209)
        at jdk.testlibrary.Asserts.assertEquals(Asserts.java:193)
        at jdk.testlibrary.Asserts.assertEQ(Asserts.java:170)
        at TestDaemon.driver(TestDaemon.java:58)
        at TestDaemon.main(TestDaemon.java:22)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:955)
```


[test-2.log](https://github.com/alibaba/dragonwell11/files/9239718/test-2.log)
