### ISSUE TITLE
sun/security/provider/SecureRandom/AbstractDrbg/SpecTest.java intermittently timeout

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell11#322]
**Describe the bug**
sun/security/provider/SecureRandom/AbstractDrbg/SpecTest.java intermittently fail. When the /dev/random is empty, then this testcase will run timeout

**To Reproduce**
1. make /proc/sys/kernel/random/entropy_avail small than 1000
```bash
wc -l /dev/random
cat /proc/sys/kernel/random/entropy_avail
```
![image](https://user-images.githubusercontent.com/24123821/199694086-11ed8941-9c8f-481b-9a09-4ce620879078.png)

3. run the test
```bash
rm -rf tmp/ ; jtreg -nr -v:fail,error -w tmp -timeout:0.1 test/jdk/sun/security/provider/SecureRandom/AbstractDrbg/SpecTest.java
```

**result**
```log
ACTION: main -- Error. Program `/home/yansendao/software/jdk/temurin/jdk-11.0.17+8/bin/java' timed out (timeout set to 12000ms, elapsed time including timeout handling was 12400ms).
REASON: User specified action: run main SpecTest 
TIME:   12.403 seconds
messages:
command: main SpecTest
reason: User specified action: run main SpecTest 
Mode: othervm [test or library overrides a system module]
Additional options from @modules: --add-modules java.base --add-exports java.base/sun.security.provider=ALL-UNNAMED
Timeout information:
Running jstack on process 807522
2022-11-03 18:08:10
Full thread dump OpenJDK 64-Bit Server VM (11.0.17+8 mixed mode):

Threads class SMR info:
_java_thread_list=0x0000fffef4001ec0, length=12, elements={
0x0000ffff84028800, 0x0000ffff844ef800, 0x0000ffff844f3800, 0x0000ffff84508800,
0x0000ffff8450a800, 0x0000ffff8450d000, 0x0000ffff8450f000, 0x0000ffff84511000,
0x0000ffff8454e800, 0x0000fffef006d000, 0x0000ffff8463a000, 0x0000fffef4001000
}

"main" #1 prio=5 os_prio=0 cpu=141.21ms elapsed=12.37s tid=0x0000ffff84028800 nid=0xc5264 in Object.wait()  [0x0000ffff8b5af000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.17/Native Method)
        - waiting on <0x0000000101a0d398> (a java.lang.Thread)
        at java.lang.Thread.join(java.base@11.0.17/Thread.java:1300)
        - waiting to re-lock in wait() <0x0000000101a0d398> (a java.lang.Thread)
        at java.lang.Thread.join(java.base@11.0.17/Thread.java:1375)
        at com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=0.18ms elapsed=12.35s tid=0x0000ffff844ef800 nid=0xc526c waiting on condition  [0x0000ffff12ef5000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.17/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@11.0.17/Reference.java:241)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.17/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.48ms elapsed=12.35s tid=0x0000ffff844f3800 nid=0xc526d in Object.wait()  [0x0000ffff12cf5000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.17/Native Method)
        - waiting on <0x0000000101c09008> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.17/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x0000000101c09008> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.17/ReferenceQueue.java:176)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.17/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.33ms elapsed=12.34s tid=0x0000ffff84508800 nid=0xc526e runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=0.09ms elapsed=12.34s tid=0x0000ffff8450a800 nid=0xc526f runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=0 cpu=45.74ms elapsed=12.34s tid=0x0000ffff8450d000 nid=0xc5270 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #18 daemon prio=9 os_prio=0 cpu=49.63ms elapsed=12.34s tid=0x0000ffff8450f000 nid=0xc5271 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #24 daemon prio=9 os_prio=0 cpu=0.11ms elapsed=12.34s tid=0x0000ffff84511000 nid=0xc5272 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #25 daemon prio=8 os_prio=0 cpu=0.16ms elapsed=12.32s tid=0x0000ffff8454e800 nid=0xc5273 in Object.wait()  [0x0000ffff11b85000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.17/Native Method)
        - waiting on <0x0000000101c449d8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.17/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x0000000101c449d8> (a java.lang.ref.ReferenceQueue$Lock)
        at jdk.internal.ref.CleanerImpl.run(java.base@11.0.17/CleanerImpl.java:148)
        at java.lang.Thread.run(java.base@11.0.17/Thread.java:829)
        at jdk.internal.misc.InnocuousThread.run(java.base@11.0.17/InnocuousThread.java:161)

"C1 CompilerThread1" #19 daemon prio=9 os_prio=0 cpu=35.85ms elapsed=12.29s tid=0x0000fffef006d000 nid=0xc5274 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"MainThread" #27 prio=5 os_prio=0 cpu=44.95ms elapsed=12.23s tid=0x0000ffff8463a000 nid=0xc5276 runnable  [0x0000ffff11582000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.readBytes(java.base@11.0.17/Native Method)
        at java.io.FileInputStream.read(java.base@11.0.17/FileInputStream.java:279)
        at java.io.FilterInputStream.read(java.base@11.0.17/FilterInputStream.java:133)
        at sun.security.provider.SeedGenerator$URLSeedGenerator.getSeedBytes(java.base@11.0.17/SeedGenerator.java:541)
        at sun.security.provider.SeedGenerator.generateSeed(java.base@11.0.17/SeedGenerator.java:144)
        at sun.security.provider.AbstractDrbg.lambda$static$0(java.base@11.0.17/AbstractDrbg.java:524)
        at sun.security.provider.AbstractDrbg$$Lambda$41/0x000000080007b040.getEntropy(java.base@11.0.17/Unknown Source)
        at sun.security.provider.AbstractDrbg.getEntropyInput(java.base@11.0.17/AbstractDrbg.java:507)
        at sun.security.provider.AbstractDrbg.getEntropyInput(java.base@11.0.17/AbstractDrbg.java:494)
        at sun.security.provider.AbstractDrbg.instantiateIfNecessary(java.base@11.0.17/AbstractDrbg.java:696)
        - locked <0x00000001014de8f8> (a sun.security.provider.S$Impl3)
        at sun.security.provider.AbstractDrbg.engineNextBytes(java.base@11.0.17/AbstractDrbg.java:378)
        at sun.security.provider.S.engineNextBytes(java.base@11.0.17/S.java:138)
        at java.security.SecureRandom.nextBytes(java.base@11.0.17/SecureRandom.java:782)
        - locked <0x00000001014de968> (a java.security.SecureRandom)
        at SpecTest.main(SpecTest.java:119)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.17/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.17/NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.17/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@11.0.17/Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(java.base@11.0.17/Thread.java:829)

"Attach Listener" #28 daemon prio=9 os_prio=0 cpu=0.27ms elapsed=0.10s tid=0x0000fffef4001000 nid=0xc5295 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=0 cpu=1.01ms elapsed=12.36s tid=0x0000ffff844e7800 nid=0xc526b runnable  

"GC Thread#0" os_prio=0 cpu=0.70ms elapsed=12.37s tid=0x0000ffff84043000 nid=0xc5266 runnable  

"G1 Main Marker" os_prio=0 cpu=0.18ms elapsed=12.37s tid=0x0000ffff840b4000 nid=0xc5267 runnable  

"G1 Conc#0" os_prio=0 cpu=0.08ms elapsed=12.37s tid=0x0000ffff840b6000 nid=0xc5268 runnable  

"G1 Refine#0" os_prio=0 cpu=0.20ms elapsed=12.37s tid=0x0000ffff8447a800 nid=0xc5269 runnable  

"G1 Young RemSet Sampling" os_prio=0 cpu=0.48ms elapsed=12.37s tid=0x0000ffff8447c800 nid=0xc526a runnable  
"VM Periodic Task Thread" os_prio=0 cpu=1.23ms elapsed=12.25s tid=0x0000ffff8460b000 nid=0xc5275 waiting on condition  

JNI global refs: 33, weak refs: 0

--- Timeout information end.
elapsed time (seconds): 12.403
```

**Additional context**
```
java -version
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)


git remote -v ; git branch ; git log -n 1
origin  git@github.com:adoptium/jdk11u.git (fetch)
origin  git@github.com:adoptium/jdk11u.git (push)
* master
commit b928a88fd564fab88f00086a62c0695ed5cc9353 (HEAD -> master, tag: jdk-11.0.18+1, origin/master, origin/HEAD)
Author: Ichiroh Takiguchi <itakiguchi@openjdk.org>
Date:   Tue Nov 1 04:50:09 2022 +0000

    8292899: CustomTzIDCheckDST.java testcase failed on AIX platform
    
    Backport-of: 3464019d7e8fe57adc910339c00ba79884c77852
```

mine solution: change /dev/random to /dev/urandom

![image](https://user-images.githubusercontent.com/24123821/199694919-f9dce9cc-372e-44f3-ba38-10865ba0d514.png)

**Comment by sendaoYan** [comment]
http://ci.dragonwell-jdk.io/job/Test_openjdk11_dragonwell_extended.openjdk_aarch64_linux/19/consoleFull
