### ISSUE TITLE
[Bug] compiler/arraycopy/stress/TestStressArrayCopy.java run timeout with -Xcomp

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell11#356]
**Description**
compiler/arraycopy/stress/TestStressArrayCopy.java run timeout with -Xcomp

```
ACTION: main -- Error. Program `/tmp/tone/run/jtreg11/binary-download/jdk-11.0.17+8/bin/java' timed out (timeout set to 28800000ms, elapsed time including timeout handling was 28800291ms).
REASON: User specified action: run main/othervm/timeout=7200 -Xbootclasspath/a:. -XX:+UnlockDiagnosticVMOptions -XX:+WhiteBoxAPI compiler.arraycopy.stress.TestStressArrayCopy 
TIME:   28800.292 seconds
messages:
command: main -Xbootclasspath/a:. -XX:+UnlockDiagnosticVMOptions -XX:+WhiteBoxAPI compiler.arraycopy.stress.TestStressArrayCopy
reason: User specified action: run main/othervm/timeout=7200 -Xbootclasspath/a:. -XX:+UnlockDiagnosticVMOptions -XX:+WhiteBoxAPI compiler.arraycopy.stress.TestStressArrayCopy 
Mode: othervm [/othervm specified]
Timeout information:
Running jstack on process 146559
2022-12-29 05:16:33
Full thread dump OpenJDK 64-Bit Server VM (11.0.17+8 compiled mode):

Threads class SMR info:
_java_thread_list=0x00007f5870001f10, length=11, elements={
0x00007f5908029000, 0x00007f59085a5000, 0x00007f59085a9000, 0x00007f59085be800,
0x00007f59085c0800, 0x00007f59085c2800, 0x00007f59085c4800, 0x00007f59085c6800,
0x00007f5908644800, 0x00007f59086b1800, 0x00007f5870001000
}

"main" #1 prio=5 os_prio=0 cpu=145.91ms elapsed=28800.28s tid=0x00007f5908029000 nid=0x23c82 in Object.wait()  [0x00007f590f993000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.17/Native Method)
	- waiting on <no object reference available>
	at java.lang.Thread.join(java.base@11.0.17/Thread.java:1300)
	- waiting to re-lock in wait() <0x00000000fb8028f0> (a java.lang.Thread)
	at java.lang.Thread.join(java.base@11.0.17/Thread.java:1375)
	at com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=0.39ms elapsed=28800.26s tid=0x00007f59085a5000 nid=0x23c89 waiting on condition  [0x00007f588dde1000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.17/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@11.0.17/Reference.java:241)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.17/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.42ms elapsed=28800.26s tid=0x00007f59085a9000 nid=0x23c8a in Object.wait()  [0x00007f588dce0000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.17/Native Method)
	- waiting on <0x00000000fb80b450> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.17/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x00000000fb80b450> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.17/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.17/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.68ms elapsed=28800.25s tid=0x00007f59085be800 nid=0x23c8b runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=0.07ms elapsed=28800.25s tid=0x00007f59085c0800 nid=0x23c8c runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=0 cpu=2517.11ms elapsed=28800.25s tid=0x00007f59085c2800 nid=0x23c8d waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #20 daemon prio=9 os_prio=0 cpu=1362.59ms elapsed=28800.25s tid=0x00007f59085c4800 nid=0x23c8e waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #27 daemon prio=9 os_prio=0 cpu=3.41ms elapsed=28800.25s tid=0x00007f59085c6800 nid=0x23c8f runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #28 daemon prio=8 os_prio=0 cpu=7.72ms elapsed=28799.37s tid=0x00007f5908644800 nid=0x23d38 in Object.wait()  [0x00007f588d5d8000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.17/Native Method)
	- waiting on <no object reference available>
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.17/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x00000000fb882338> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@11.0.17/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@11.0.17/Thread.java:829)
	at jdk.internal.misc.InnocuousThread.run(java.base@11.0.17/InnocuousThread.java:161)

"MainThread" #30 prio=5 os_prio=0 cpu=301.22ms elapsed=28798.63s tid=0x00007f59086b1800 nid=0x23e18 in Object.wait()  [0x00007f588d1fd000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.17/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@11.0.17/Object.java:328)
	at java.lang.ProcessImpl.waitFor(java.base@11.0.17/ProcessImpl.java:495)
	- waiting to re-lock in wait() <0x00000000fb8a4f40> (a java.lang.ProcessImpl)
	at jdk.test.lib.process.OutputBuffer$LazyOutputBuffer.getExitValue(OutputBuffer.java:124)
	at jdk.test.lib.process.OutputAnalyzer.getExitValue(OutputAnalyzer.java:523)
	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:429)
	at compiler.arraycopy.stress.TestStressArrayCopy.main(TestStressArrayCopy.java:201)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.17/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.17/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.17/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.17/Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(java.base@11.0.17/Thread.java:829)

"Attach Listener" #424 daemon prio=9 os_prio=0 cpu=0.16ms elapsed=0.09s tid=0x00007f5870001000 nid=0x9c634 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=0 cpu=318.43ms elapsed=28800.26s tid=0x00007f590859d000 nid=0x23c88 runnable  

"GC Thread#0" os_prio=0 cpu=23.11ms elapsed=28800.28s tid=0x00007f5908047800 nid=0x23c83 runnable  

"GC Thread#1" os_prio=0 cpu=24.95ms elapsed=28796.37s tid=0x00007f5884001000 nid=0x24217 runnable  

"GC Thread#2" os_prio=0 cpu=16.76ms elapsed=28796.37s tid=0x00007f5884003000 nid=0x24218 runnable  

"GC Thread#3" os_prio=0 cpu=21.89ms elapsed=28796.37s tid=0x00007f5884004800 nid=0x24219 runnable  

"GC Thread#4" os_prio=0 cpu=19.20ms elapsed=28796.36s tid=0x00007f5884006800 nid=0x24226 runnable  

"GC Thread#5" os_prio=0 cpu=14.98ms elapsed=28796.36s tid=0x00007f5884008000 nid=0x2422c runnable  

"GC Thread#6" os_prio=0 cpu=23.57ms elapsed=28796.36s tid=0x00007f588400a000 nid=0x24234 runnable  

"GC Thread#7" os_prio=0 cpu=20.30ms elapsed=28796.36s tid=0x00007f588400c000 nid=0x24236 runnable  

"GC Thread#8" os_prio=0 cpu=12.32ms elapsed=28796.36s tid=0x00007f588400d800 nid=0x2423a runnable  

"GC Thread#9" os_prio=0 cpu=21.46ms elapsed=28796.36s tid=0x00007f588400f800 nid=0x2423c runnable  

"GC Thread#10" os_prio=0 cpu=22.84ms elapsed=28796.35s tid=0x00007f5884011000 nid=0x24241 runnable  

"GC Thread#11" os_prio=0 cpu=23.36ms elapsed=28796.35s tid=0x00007f5884013000 nid=0x24245 runnable  

"GC Thread#12" os_prio=0 cpu=38.40ms elapsed=28796.35s tid=0x00007f5884014800 nid=0x24246 runnable  

"GC Thread#13" os_prio=0 cpu=39.60ms elapsed=28796.35s tid=0x00007f5884016800 nid=0x24247 runnable  

"GC Thread#14" os_prio=0 cpu=38.98ms elapsed=28796.35s tid=0x00007f5884018800 nid=0x24249 runnable  

"GC Thread#15" os_prio=0 cpu=17.31ms elapsed=28796.35s tid=0x00007f588401a000 nid=0x2424a runnable  

"GC Thread#16" os_prio=0 cpu=20.87ms elapsed=28796.35s tid=0x00007f588401c000 nid=0x2424b runnable  

"GC Thread#17" os_prio=0 cpu=24.51ms elapsed=28796.35s tid=0x00007f588401d800 nid=0x2424d runnable  

"GC Thread#18" os_prio=0 cpu=25.95ms elapsed=28796.35s tid=0x00007f588401f800 nid=0x2424e runnable  

"GC Thread#19" os_prio=0 cpu=23.23ms elapsed=28796.34s tid=0x00007f5884021000 nid=0x2425b runnable  

"GC Thread#20" os_prio=0 cpu=24.56ms elapsed=28796.34s tid=0x00007f5884023000 nid=0x2425c runnable  

"GC Thread#21" os_prio=0 cpu=28.76ms elapsed=28796.34s tid=0x00007f5884025000 nid=0x2425d runnable  

"GC Thread#22" os_prio=0 cpu=24.58ms elapsed=28796.34s tid=0x00007f5884026800 nid=0x2425e runnable  

"GC Thread#23" os_prio=0 cpu=23.76ms elapsed=28796.34s tid=0x00007f5884028800 nid=0x24260 runnable  

"GC Thread#24" os_prio=0 cpu=19.30ms elapsed=28796.34s tid=0x00007f588402a000 nid=0x24261 runnable  

"GC Thread#25" os_prio=0 cpu=26.64ms elapsed=28796.34s tid=0x00007f588402c000 nid=0x24263 runnable  

"GC Thread#26" os_prio=0 cpu=11.75ms elapsed=28796.34s tid=0x00007f588402d800 nid=0x24265 runnable  

"GC Thread#27" os_prio=0 cpu=12.21ms elapsed=28796.34s tid=0x00007f588402f800 nid=0x2426a runnable  

"GC Thread#28" os_prio=0 cpu=19.51ms elapsed=28796.34s tid=0x00007f5884031800 nid=0x2426b runnable  

"GC Thread#29" os_prio=0 cpu=24.23ms elapsed=28796.34s tid=0x00007f5884033000 nid=0x2426c runnable  

"GC Thread#30" os_prio=0 cpu=15.71ms elapsed=28796.34s tid=0x00007f5884035000 nid=0x2426d runnable  

"GC Thread#31" os_prio=0 cpu=24.87ms elapsed=28796.34s tid=0x00007f5884036800 nid=0x2426e runnable  

"GC Thread#32" os_prio=0 cpu=25.29ms elapsed=28796.33s tid=0x00007f5884038800 nid=0x2426f runnable  

"GC Thread#33" os_prio=0 cpu=24.99ms elapsed=28796.33s tid=0x00007f588403a000 nid=0x24270 runnable  

"GC Thread#34" os_prio=0 cpu=26.26ms elapsed=28796.33s tid=0x00007f588403c000 nid=0x24271 runnable  

"GC Thread#35" os_prio=0 cpu=23.13ms elapsed=28796.33s tid=0x00007f588403e000 nid=0x24272 runnable  

"GC Thread#36" os_prio=0 cpu=31.60ms elapsed=28796.33s tid=0x00007f588403f800 nid=0x24273 runnable  

"GC Thread#37" os_prio=0 cpu=17.28ms elapsed=28796.33s tid=0x00007f5884041800 nid=0x24275 runnable  

"GC Thread#38" os_prio=0 cpu=20.02ms elapsed=28796.33s tid=0x00007f5884043000 nid=0x24276 runnable  

"GC Thread#39" os_prio=0 cpu=20.48ms elapsed=28796.33s tid=0x00007f5884045000 nid=0x24277 runnable  

"GC Thread#40" os_prio=0 cpu=25.77ms elapsed=28796.33s tid=0x00007f5884046800 nid=0x24278 runnable  

"GC Thread#41" os_prio=0 cpu=20.32ms elapsed=28796.33s tid=0x00007f5884048800 nid=0x24279 runnable  

"GC Thread#42" os_prio=0 cpu=18.78ms elapsed=28796.33s tid=0x00007f588404a000 nid=0x2427a runnable  

"GC Thread#43" os_prio=0 cpu=15.97ms elapsed=28796.33s tid=0x00007f588404c000 nid=0x2427b runnable  

"GC Thread#44" os_prio=0 cpu=7.17ms elapsed=28796.33s tid=0x00007f588404e000 nid=0x2427c runnable  

"GC Thread#45" os_prio=0 cpu=6.73ms elapsed=28796.33s tid=0x00007f588404f800 nid=0x2427e runnable  

"GC Thread#46" os_prio=0 cpu=11.59ms elapsed=28796.33s tid=0x00007f5884051800 nid=0x24282 runnable  

"GC Thread#47" os_prio=0 cpu=9.18ms elapsed=28796.33s tid=0x00007f5884053000 nid=0x24287 runnable  

"GC Thread#48" os_prio=0 cpu=15.63ms elapsed=28796.33s tid=0x00007f5884055000 nid=0x2428a runnable  

"G1 Main Marker" os_prio=0 cpu=0.27ms elapsed=28800.28s tid=0x00007f59080bc000 nid=0x23c84 runnable  

"G1 Conc#0" os_prio=0 cpu=0.04ms elapsed=28800.28s tid=0x00007f59080be000 nid=0x23c85 runnable  

"G1 Refine#0" os_prio=0 cpu=0.20ms elapsed=28800.27s tid=0x00007f590852a000 nid=0x23c86 runnable  

"G1 Young RemSet Sampling" os_prio=0 cpu=1468.16ms elapsed=28800.27s tid=0x00007f590852b800 nid=0x23c87 runnable  
"VM Periodic Task Thread" os_prio=0 cpu=2339.08ms elapsed=28799.52s tid=0x00007f590861b800 nid=0x23d2b waiting on condition  

JNI global refs: 26, weak refs: 0

Timeout refired 28800 times
STDERR:
Exception in thread "process reaper" java.lang.StackOverflowError
	at java.base/java.util.concurrent.ConcurrentHashMap.fullAddCount(ConcurrentHashMap.java:2574)
	at java.base/java.util.concurrent.ConcurrentHashMap.addCount(ConcurrentHashMap.java:2326)
	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1173)
	at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102)
	at java.base/java.lang.invoke.MethodType$ConcurrentWeakInternSet.expungeStaleElements(MethodType.java:1318)
	at java.base/java.lang.invoke.MethodType$ConcurrentWeakInternSet.get(MethodType.java:1277)
	at java.base/java.lang.invoke.MethodType.makeImpl(MethodType.java:300)
	at java.base/java.lang.invoke.MethodHandleNatives.findMethodHandleType(MethodHandleNatives.java:376)
	at java.base/java.util.concurrent.CompletableFuture.completeValue(CompletableFuture.java:305)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2072)
	at java.base/java.lang.ProcessHandleImpl$1.run(ProcessHandleImpl.java:162)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Steps to Reproduce**
jtreg -va -nr -w tmp -timeout:4 -vmoptions:"-Xcomp" test/hotspot/jtreg/compiler/arraycopy/stress/TestStressArrayCopy.java

**Expected behavior**
run pass

**JDK version**
```
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)
```

**Execution environment**

![image](https://user-images.githubusercontent.com/24123821/209903366-f502bf42-6049-4e78-94a9-692f8c082e0a.png)

[jtreg-result.log](https://github.com/alibaba/dragonwell11/files/10317575/jtreg-result.log)

**Comment by sendaoYan** [comment]
单跑没有复现

**Comment by sendaoYan** [comment]
随机出现，待统计随机出现概率

**Comment by sendaoYan** [comment]
> 随机出现，待统计随机出现概率

复现概率50%
```bash
for i in `seq 10` ; do jtreg -va -nr -w tmp -timeout:1 -vmoptions:"-Xcomp" test/hotspot/jtreg/compiler/arraycopy/stress/TestStressArrayCopy.java &> TestStressArrayCopy-$i.log ; done                     
```
![image](https://user-images.githubusercontent.com/24123821/210052806-48bf2354-1422-4c5e-ba8a-8a0e075a107a.png)
[TestStressArrayCopy-9.log](https://github.com/alibaba/dragonwell11/files/10323757/TestStressArrayCopy-9.log)
[TestStressArrayCopy-8.log](https://github.com/alibaba/dragonwell11/files/10323758/TestStressArrayCopy-8.log)
[TestStressArrayCopy-7.log](https://github.com/alibaba/dragonwell11/files/10323759/TestStressArrayCopy-7.log)
[TestStressArrayCopy-6.log](https://github.com/alibaba/dragonwell11/files/10323760/TestStressArrayCopy-6.log)
[TestStressArrayCopy-5.log](https://github.com/alibaba/dragonwell11/files/10323762/TestStressArrayCopy-5.log)
[TestStressArrayCopy-4.log](https://github.com/alibaba/dragonwell11/files/10323764/TestStressArrayCopy-4.log)
[TestStressArrayCopy-3.log](https://github.com/alibaba/dragonwell11/files/10323765/TestStressArrayCopy-3.log)
[TestStressArrayCopy-2.log](https://github.com/alibaba/dragonwell11/files/10323766/TestStressArrayCopy-2.log)
[TestStressArrayCopy-1.log](https://github.com/alibaba/dragonwell11/files/10323767/TestStressArrayCopy-1.log)
[TestStressArrayCopy-10.log](https://github.com/alibaba/dragonwell11/files/10323768/TestStressArrayCopy-10.log)

```
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)
```

**Comment by sendaoYan** [comment]
待统计jdk21的复现概率
