### ISSUE TITLE
-Xcomp选项运行com/alibaba/wisp/bug/CancelTimerAndSleepTest.java用例随机失败

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell11#407]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/147258?tab=1

 ```
STDOUT:
STDERR:
java.lang.Error: elapsed = 10
	at CancelTimerAndSleepTest.main(CancelTimerAndSleepTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:855)

JavaTest Message: Test threw exception: java.lang.Error: elapsed = 10
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.Error: elapsed = 10
rerun:
cd /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp/bug/CancelTimerAndSleepTest && \
DISPLAY=:7 \
HOME=/root \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
CLASSPATH=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/85/com/alibaba/wisp/bug:/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/bug:/opt/java/openjdk/lib/tools.jar:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /opt/java/openjdk/bin/java \
        -Dtest.vm.opts='-Xcomp -ea -esa' \
        -Dtest.tool.vm.opts='-J-Xcomp -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/opt/java/openjdk \
        -Dcompile.jdk=/opt/java/openjdk \
        -Dtest.timeout.factor=4.0 \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/jdk/test \
        -Dtest.name=com/alibaba/wisp/bug/CancelTimerAndSleepTest.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/bug/CancelTimerAndSleepTest.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/bug \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/bug \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/85/com/alibaba/wisp/bug \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/85/com/alibaba/wisp/bug \
        -Xcomp \
        -ea \
        -esa \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+EnableCoroutine \
        -Dcom.alibaba.wisp.transparentWispSwitch=true \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp/bug/CancelTimerAndSleepTest.d/main.0.jta

TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Error: elapsed = 10
```
[9.log](https://github.com/alibaba/dragonwell11/files/10782925/9.log)
[8.log](https://github.com/alibaba/dragonwell11/files/10782926/8.log)
[7.log](https://github.com/alibaba/dragonwell11/files/10782927/7.log)
[6.log](https://github.com/alibaba/dragonwell11/files/10782928/6.log)
[5.log](https://github.com/alibaba/dragonwell11/files/10782929/5.log)
[50.log](https://github.com/alibaba/dragonwell11/files/10782930/50.log)
[4.log](https://github.com/alibaba/dragonwell11/files/10782931/4.log)
[49.log](https://github.com/alibaba/dragonwell11/files/10782932/49.log)
[48.log](https://github.com/alibaba/dragonwell11/files/10782933/48.log)

replay command:
```
test=jdk/test/com/alibaba/wisp/bug/CancelTimerAndSleepTest.java
nproc=`nproc` ; dir="tmp-jtreg-"`basename $test .java` ; rm -rf $dir ; mkdir -p $dir ; time seq 50 | xargs -i -n 1 -P $nproc bash -c "jtreg -Xcomp -ea -esa -timeoutFactor:4 -v:fail,error,time,nopass -nr -w $dir/index-{} $test &> $dir/{}.log ; grep 'Test results: passed: 1' -L $dir/{}.log"
```

**Comment by sendaoYan** [comment]
aarch64平台-Xcomp连续跑5次均fail：

https://tone.aliyun-inc.com/ws/xesljfzh/test_result/153929?tab=1
