### ISSUE TITLE
【上游问题】-Xcomp选项运行com/sun/tools/attach/PermissionTest.java随机栈溢出

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell11#417]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/147395?tab=2

```log
Exception in thread "process reaper" java.lang.StackOverflowError
	at java.base/java.util.concurrent.ConcurrentHashMap.fullAddCount(ConcurrentHashMap.java:2574)
	at java.base/java.util.concurrent.ConcurrentHashMap.addCount(ConcurrentHashMap.java:2326)
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1075)
	at java.base/java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1541)
	at java.base/java.lang.invoke.MethodType$ConcurrentWeakInternSet.add(MethodType.java:1309)
	at java.base/java.lang.invoke.MethodType.makeImpl(MethodType.java:316)
	at java.base/java.lang.invoke.MethodHandleNatives.findMethodHandleType(MethodHandleNatives.java:376)
	at java.base/java.util.concurrent.CompletableFuture.completeValue(CompletableFuture.java:305)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2072)
	at java.base/java.lang.ProcessHandleImpl$1.run(ProcessHandleImpl.java:162)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sendaoYan** [comment]
com/sun/jdi/RedefineStep.java

https://tone.aliyun-inc.com/ws/xesljfzh/test_result/152802?tab=2

```
STDOUT:
Command line: [/opt/java/openjdk/bin/java -cp /tmp/tone/run/jtreg/jt-work/test_jdk/classes/170/com/sun/jdi/RedefineStep.d:/tmp/tone/run/jtreg/jdk-repo/test/jdk/com/sun/jdi:/tmp/tone/run/jtreg/jt-work/test_jdk/classes/170/test/lib:/tmp/tone/run/jtreg/jdk-repo/test/lib:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar -Xcomp -ea -esa -agentlib:jdwp=transport=dt_socket,server=y,suspend=y RedefineStepTarg ]
[debuggee]:/opt/java/openjdk/bin/java -cp /tmp/tone/run/jtreg/jt-work/test_jdk/classes/170/com/sun/jdi/RedefineStep.d:/tmp/tone/run/jtreg/jdk-repo/test/jdk/com/sun/jdi:/tmp/tone/run/jtreg/jt-work/test_jdk/classes/170/test/lib:/tmp/tone/run/jtreg/jdk-repo/test/lib:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar -Xcomp -ea -esa -agentlib:jdwp=transport=dt_socket,server=y,suspend=y RedefineStepTarg
[debuggee] Listening for transport dt_socket at address: 56343
[jdb] Set uncaught java.lang.Throwable
[jdb] Set deferred uncaught java.lang.Throwable
[jdb] Initializing jdb ...
[jdb] 
[jdb] VM Started: > No frames on the current call stack
[jdb] 
[jdb] main[1] 
> stop at RedefineStepTarg:48
[jdb] Deferring breakpoint RedefineStepTarg:48.
[jdb] It will be set after the class is loaded.
[jdb] main[1] 
> run 
[jdb] > Set deferred breakpoint RedefineStepTarg:48
[jdb] 
[jdb] Breakpoint hit: "thread=main", RedefineStepTarg.a1(), line=48 bci=0
[jdb] 48            System.out.println("jj0");   // @1 breakpoint   line 10
[jdb] 
[jdb] main[1] 
> redefine RedefineStepTarg ./ver1/RedefineStepTarg.class
[jdb] main[1] 
> next
[jdb] > 
[jdb] Step completed: "thread=main", RedefineStepTarg.<obsolete>(), line=-1 bci=3
[jdb] 
[jdb] main[1] 
> next
[jdb] > 
[jdb] Step completed: "thread=main", RedefineStepTarg.<obsolete>(), line=-1 bci=5
[jdb] 
[jdb] main[1] 
> next
[debuggee] jj0
[jdb] > 
[jdb] Step completed: "thread=main", RedefineStepTarg.<obsolete>(), line=-1 bci=8
[jdb] 
[jdb] main[1] 
> next
[jdb] > 
[jdb] Step completed: "thread=main", RedefineStepTarg.<obsolete>(), line=-1 bci=9
[jdb] 
[jdb] main[1] 
> next
[debuggee] a2
[jdb] > 
[jdb] Step completed: "thread=main", RedefineStepTarg.<obsolete>(), line=-1 bci=12
[jdb] 
[jdb] main[1] 
> quit
[debuggee] jj3
[debuggee] Listening for transport dt_socket at address: 60327
[debuggee] done
STDERR:
Exception in thread "process reaper" java.lang.StackOverflowError
	at java.base/java.util.concurrent.ConcurrentHashMap.fullAddCount(ConcurrentHashMap.java:2574)
	at java.base/java.util.concurrent.ConcurrentHashMap.addCount(ConcurrentHashMap.java:2326)
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1075)
	at java.base/java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1541)
	at java.base/java.lang.invoke.MethodType$ConcurrentWeakInternSet.add(MethodType.java:1309)
	at java.base/java.lang.invoke.MethodType.makeImpl(MethodType.java:316)
	at java.base/java.lang.invoke.MethodHandleNatives.findMethodHandleType(MethodHandleNatives.java:376)
	at java.base/java.util.concurrent.CompletableFuture.completeValue(CompletableFuture.java:305)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2072)
	at java.base/java.lang.ProcessHandleImpl$1.run(ProcessHandleImpl.java:162)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:955)
java.lang.RuntimeException: waitForPrompt timed out after 240 seconds, looking for '[a-zA-Z0-9_-][a-zA-Z0-9_-]*\[[1-9][0-9]*\] [ >]*$', in 1 lines
	at lib.jdb.Jdb.waitForPrompt(Jdb.java:205)
	at lib.jdb.Jdb.waitForPrompt(Jdb.java:156)
	at lib.jdb.Jdb.command(Jdb.java:226)
	at lib.jdb.Jdb.quit(Jdb.java:251)
	at lib.jdb.Jdb.shutdown(Jdb.java:106)
	at lib.jdb.JdbTest.shutdown(JdbTest.java:129)
	at lib.jdb.JdbTest.run(JdbTest.java:97)
	at RedefineStep.main(RedefineStep.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:955)

JavaTest Message: Test threw exception: java.lang.RuntimeException: waitForPrompt timed out after 240 seconds, looking for '[a-zA-Z0-9_-][a-zA-Z0-9_-]*\[[1-9][0-9]*\] [ >]*$', in 1 lines
JavaTest Message: shutting down test
```
