### ISSUE TITLE
aarch

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell11#419]
**Description**

**Steps to Reproduce**
1. Save below snippet '...'
2. Compile it with javac '....'
3. Execute with VM options '....'

**Expected behavior**

**JDK version**
The output of `java -version` command

**Execution environment**
 - OS and version:
 - CPU model:
 - Number of CPU cores:
 - Size of physical memory:
 - Inside Linux container?
   - Linux container name (docker, pouch, etc):
   - Linux container version:

**Comment by sendaoYan** [comment]
com/alibaba/wisp/exclusive/lock/TestLock.java

```log
java.lang.RuntimeException: assertTrue: expected true, was false
	at jdk.testlibrary.Asserts.fail(Asserts.java:540)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:490)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:476)
	at TestLock.main(TestLock.java:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:955)
```

**Comment by sendaoYan** [comment]
-Xmixed: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148517?tab=3

**Comment by sendaoYan** [comment]
-Xmixed: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148982

**Comment by sendaoYan** [comment]
-Xcomp连续5次均失败：

https://tone.aliyun-inc.com/ws/xesljfzh/test_result/153934

[jtreg-result-rerun.log](https://github.com/alibaba/dragonwell11/files/10939409/jtreg-result-rerun.log)
