### ISSUE TITLE
【regress】-Xcomp选项运行compiler/aot/cli/jaotc/AtFileTest.java用例报错Could not initialize class com.alibaba.wisp.engine.WispEngine

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell11#424]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/147355?tab=1

```log
Exception in thread "process reaper" java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.wisp.engine.WispEngine
	at java.base/java.util.concurrent.SynchronousQueue$TransferStack.shouldSpin(SynchronousQueue.java:478)
	at java.base/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:443)
	at java.base/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:367)
	at java.base/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:948)
	at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:955)
```

temurin11:

![image](https://user-images.githubusercontent.com/24123821/220542661-63786ea1-74c4-4cf7-a109-254959c10903.png)

**Comment by sendaoYan** [comment]
如下10个用例归类为同一个问题：

```
compiler/aot/cli/jaotc/AtFileTest.java
compiler/aot/cli/jaotc/CompileClassTest.java
compiler/aot/cli/jaotc/CompileClassWithDebugTest.java
compiler/aot/cli/jaotc/CompileDirectoryTest.java
compiler/aot/cli/jaotc/CompileJarTest.java
compiler/aot/cli/jaotc/CompileModuleTest.java
compiler/aot/cli/jaotc/IgnoreErrorsTest.java
compiler/aot/cli/jaotc/ListOptionTest.java
compiler/aot/cli/jaotc/ListOptionWrongFileTest.java
compiler/aot/fingerprint/SelfChangedCDS.java
```
