### ISSUE TITLE
com/alibaba/wisp/exclusive/thread/TestDaemon.java随机失败

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell11#471]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148193?tab=1

```log
STDOUT:
STDERR:
Note: /tmp/tone/run/jtreg/jdk-repo/test/jdk/com/alibaba/wisp/exclusive/thread/TestDaemon.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: assertEquals: expected true to equal false
REASON: User specified action: run main TestDaemon 
TIME:   3.97 seconds
messages:
command: main TestDaemon
reason: User specified action: run main TestDaemon 
Mode: othervm
elapsed time (seconds): 3.97
configuration:
STDOUT:
STDERR:
java.lang.RuntimeException: assertEquals: expected true to equal false
	at jdk.testlibrary.Asserts.fail(Asserts.java:540)
	at jdk.testlibrary.Asserts.assertEquals(Asserts.java:209)
	at jdk.testlibrary.Asserts.assertEquals(Asserts.java:193)
	at jdk.testlibrary.Asserts.assertEQ(Asserts.java:170)
	at TestDaemon.driver(TestDaemon.java:59)
	at TestDaemon.main(TestDaemon.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:991)

JavaTest Message: Test threw exception: java.lang.RuntimeException: assertEquals: expected true to equal false
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: assertEquals: expected true to equal false
rerun:
cd /tmp/tone/run/jtreg/jt-work/test_jdk/com/alibaba/wisp/exclusive/thread/TestDaemon && \
DISPLAY=:7 \
HOME=/home/testUserForTone \
LANG=C \
LC_CTYPE=C.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
TEST_IMAGE_DIR=/tmp/tone/run/jtreg/test-images/jdk-11.0.17.16+-test-image \
CLASSPATH=/tmp/tone/run/jtreg/jt-work/test_jdk/classes/167/com/alibaba/wisp/exclusive/thread/TestDaemon.d:/tmp/tone/run/jtreg/jdk-repo/test/jdk/com/alibaba/wisp/exclusive/thread:/tmp/tone/run/jtreg/jt-work/test_jdk/classes/167/test/lib:/tmp/tone/run/jtreg/jdk-repo/test/lib:/tmp/tone/run/jtreg/jt-work/test_jdk/classes/167/lib/testlibrary:/tmp/tone/run/jtreg/jdk-repo/test/jdk/lib/testlibrary:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /tmp/tone/run/jtreg/binary-download/jdk-11.0.17.16+/bin/java \
        -Dtest.vm.opts='-Xmixed -ea -esa' \
        -Dtest.tool.vm.opts='-J-Xmixed -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/tmp/tone/run/jtreg/binary-download/jdk-11.0.17.16+ \
        -Dcompile.jdk=/tmp/tone/run/jtreg/binary-download/jdk-11.0.17.16+ \
        -Dtest.timeout.factor=4.0 \
        -Dtest.nativepath=/tmp/tone/run/jtreg/test-images/jdk-11.0.17.16+-test-image/hotspot/jtreg/native \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/test/jdk \
        -Dtest.name=com/alibaba/wisp/exclusive/thread/TestDaemon.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/test/jdk/com/alibaba/wisp/exclusive/thread/TestDaemon.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/test/jdk/com/alibaba/wisp/exclusive/thread \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/test/jdk/com/alibaba/wisp/exclusive/thread:/tmp/tone/run/jtreg/jdk-repo/test/lib:/tmp/tone/run/jtreg/jdk-repo/test/jdk/lib/testlibrary \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work/test_jdk/classes/167/com/alibaba/wisp/exclusive/thread/TestDaemon.d \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work/test_jdk/classes/167/com/alibaba/wisp/exclusive/thread/TestDaemon.d:/tmp/tone/run/jtreg/jt-work/test_jdk/classes/167/test/lib:/tmp/tone/run/jtreg/jt-work/test_jdk/classes/167/lib/testlibrary \
        -Xmixed \
        -ea \
        -esa \
        -Djava.library.path=/tmp/tone/run/jtreg/test-images/jdk-11.0.17.16+-test-image/hotspot/jtreg/native \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work/test_jdk/com/alibaba/wisp/exclusive/thread/TestDaemon.d/main.0.jta

TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: assertEquals: expected true to equal false
```

![image](https://user-images.githubusercontent.com/24123821/221134691-de2e8d6d-fc59-4f5c-8413-10e2419072c7.png)

**Comment by sendaoYan** [comment]
com/alibaba/wisp2/exclusive/bug/TestPreemptWispInternalBug.java随机失败：

https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148935?tab=1

```log
STDOUT:
Command line: [/opt/java/openjdk/bin/java -cp /tmp/tone/run/jtreg/jt-work/test_jdk/classes/148/com/alibaba/wisp2/exclusive/bug/TestPreemptWispInternalBug.d:/tmp/tone/run/jtreg/jdk-repo/test/jdk/com/alibaba/wisp2/exclusive/bug:/tmp/tone/run/jtreg/jt-work/test_jdk/classes/148/test/lib:/tmp/tone/run/jtreg/jdk-repo/test/lib:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar -XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 -XX:+UnlockDiagnosticVMOptions -XX:+VerboseWisp -XX:-Inline --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED TestPreemptWispInternalBug 1 ]
[2023-02-24T10:48:17.256318Z] Gathering output for process 718041
[2023-02-24T10:48:19.071990Z] Waiting for completion for process 718041
[2023-02-24T10:48:19.072212Z] Waiting for completion finished for process 718041
STDERR:
 stdout: [];
 stderr: []
 exitValue = 0

java.lang.RuntimeException: '[WISP] preempt was blocked, because wisp internal method on the stack' missing from stdout/stderr 

	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:163)
	at TestPreemptWispInternalBug.main(TestPreemptWispInternalBug.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:955)
```
